# Generated by Django 4.2.2 on 2023-06-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0002_remove_character_role_character_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="role",
        ),
        migrations.AddField(
            model_name="character",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character",
                to="scheduler.wowrole",
            ),
        ),
    ]
