# Generated by Django 4.2.2 on 2023-06-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0003_remove_character_role_character_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="WowSecondaryRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secondary_role", models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name="character",
            old_name="role",
            new_name="primary_role",
        ),
        migrations.AddField(
            model_name="character",
            name="secondary_role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character",
                to="scheduler.wowsecondaryrole",
            ),
        ),
    ]
