# Generated by Django 4.2.2 on 2023-06-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0006_alter_character_primary_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="primary_role",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character",
                to="scheduler.wowrole",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="character",
            name="secondary_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character",
                to="scheduler.wowsecondaryrole",
            ),
        ),
    ]
