# Generated by Django 4.2.2 on 2023-06-15 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduler", "0007_alter_character_primary_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
