# Generated by Django 4.2.2 on 2023-06-15 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduler", "0009_alter_character_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
