# Generated by Django 4.2.2 on 2023-06-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0010_alter_character_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="WowTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team", models.CharField(max_length=35, null=True)),
            ],
        ),
    ]
