# Generated by Django 4.2.2 on 2023-06-15 17:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0011_wowteam"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "day",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
