# Generated by Django 4.2.2 on 2023-06-15 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0012_schedule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
