# Generated by Django 4.2.2 on 2023-06-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0013_delete_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character",
                to="scheduler.wowteam",
            ),
        ),
    ]
