# Generated by Django 4.2.2 on 2023-06-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0014_character_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character",
                to="scheduler.wowteam",
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("participants", models.ManyToManyField(to="scheduler.character")),
            ],
        ),
    ]
